markers = [
	"node_api: tests used to validate the backend app API",
	"node_api_smoke: smoke tests for the backend app API",
	"ui: tests marked to test the UI",
	"ui_smoke: tests marked to smoke test the UI",
    ]
